version: '3.8'
services:
  node-red:
    hostname: nodered
    build:
      context: ./
      dockerfile: ./dockerfiles/node-red.dockerfile
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    environment:
      - FLOWS=flows.json
    volumes:
      - ./../services/node-red:/data
      # - ./../services/node-red:/data
    depends_on:
      - influxdb

  influxdb:
    hostname: influx
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./../services/influxDB/influxdb-init:/docker-entrypoint-initdb.d
      # - ./../services/influxDB/influxdb-data:/var/lib/influxdb2

    env_file:
      - ./../env/influxdb.env
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
        

  grafana:
    hostname: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - ./../env/grafana.env
    depends_on:
      - influxdb
    volumes:
      - ../services/grafana/provisioning:/etc/grafana/provisioning
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

